# Builds, runs tests, publishes artifacts

name: Build ForcesUnite

on: push

jobs:
  comment:
    name: Comment on Merge Request
    runs-on: ubuntu-latest
    # needs: [build-api, build-spa]

    steps:
      - uses: actions/checkout@v4

      - name: Comment on Merge Request
        run: |
          branch_name=$(echo "${{ github.event.head_ref }}" | sed 's/refs\/heads\///')
          gh pr comment $branch_name -b "Tests ran successfully!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}